# **Why this report?**

In 1871, British government notified close to 200 nomadic, migratory and forest communities as 'criminal tribes' and created a system of surveillance, arrest, and detention of these communities by enacting the draconian Criminal Tribes Act. The Act gave wide ranging powers to the police and law enforcement agencies to arrest, detain and legitimize violence against these communities. It was only in the year 1950 that this draconian legislation was repealed and the communities were denotified in 1952. The Act was replaced by Habitual Offenders Act, which continued with the definition of 'habitual offenders' and the targeting of these communities has also continued. The practice of nomadism by these communities is either as a source of livelihood cultural practice. Some of these communities were forced to practice nomadism as they were ousted from their forest lands by the Brahmanical system and colonial policies. Moreover, the post-colonial legislations continue to criminalize their traditional livelihood activities and have forced them into a life of penury.

According to a Renke Commission report published in 2008, a large population among these communities are far away from socio-political and educational development. The report says people from the communities do not have records of right for their residential plots even though they are living there for generations. Demolition or eviction of their settlements by local revenue officials, municipal officials, realtors, police and the politicians are part of their struggle for survival. According to the same report, children from the communities have poor access to education and hence do not possess any certificate related to the same. The Renke commission had therefore recommended the issuing of caste certificates, BPL certificates, voting cards to these communities. As per the report, 72% of the population of nomadic and denotified tribes do not have ration card, 48% of DNTs and 60% of NTs do not have a birth certificate, 89% of the DNTs and 98% of NTs do not own land. From this study, it is evident that basic identity certificates are not accessible to people from NT-DNT communities.

In year 2019 Indian central government announced that it will conduct a national citizenship registration exercise and it has also enacted the Citizenship Amendment Act, 2019. Central government intended to start collecting data for the National Population Register (NPR), from April 1, which was delayed due to the imposition of lockdown. Pursuant to this exercise, people of the country will have to produce various identity certificates,which will go on to determine their citizenship status. Those unable to produce the documents will be notified as 'doubtful'. The documents required to establish one's claim to citizenship are not yet clear. The Assam NRC process informs us that those unable to prove their citizenship through documents, will have to approach the Courts/Tribunals set up under Foreigner's Act, 1946. Those who fail to prove their claims in courts shall be sent to detention centres set up for foreigners. This is a very brief but a broad picture of how the NRC process will unfold.     

If we foresee the impact of NPR, NRC and CAA together, we can clearly visualise the threat of 'placeless' nomadic, semi-nomadic and denotified communities becoming 'stateless'. This research will be a conscious effort to verify the inaccessibility of the nomadic, semi-nomadic and denotified communities to certificates required to establish their claim to citizenship under the NPR-NRC-CAA regime and to study its impact on further disenfranchising them.

Ever since the Citizenship Act Amendment 2019 was debated in Parliament, a large number of Muslims, Dalits and Bahujans have been opposing the law. Religious minorities such as Jains and Christians will be granted Indian citizenship if they seek asylum in India, but Muslims in these countries will not be granted Indian citizenship and the law is silent on refugees coming to India from Sri Lanka, Myanmar and other Indian border countries. After the enactment of this Act, the NRC was announced in Parliament. In order to be enrolled in the NRC, everyone has to prove that the ancestor of their family was born in India and those who cannot prove this will not be granted citizenship of India and have to apply for citizenship. In the wake of this law, those who are afraid of losing their citizenship have started a struggle against it. Meanwhile, this research will be useful to verify the relevance of the objections taken by the communities over the implementation of CAA and NRC and hence can be beneficial for the legal fight of the communities who are opposing the law.

\
