# Introduction

In the story titled 'I Think I'll Put My Son in School' from Lakshman Mane's book 'Why to Study', an individual from the Dombari community takes his child to a school to get him admitted there. While narrating this incident, he says, "I went to the school for admission. teacher asked me for a birth certificate. Saheb, tell me, what time was my child born? What day was it? Was it day or night? What village should I mention Saheb? When my wife was pregnant, we were in some field far away, near Solapur. What is the name of the field? The village? Who knows? Do I know how to read and write? Master said to bring the certificate. Which village will it come from?! None of us have ever gone to school. Father didn't educate us, neither did grandfather. There isn't a single generation in our family who studied."

Later on in the same story, during a conversation between the author and this individual, the author asks him, "What is the name of our country?" He answers, "Saheb, we don't even have a village, what country do you speak of?" (Kade, 2020)

According to the Citizenship Amendment Act, those persons whose name does not appear in the National Registry of Citizens and who are Hindu, Buddhist, Sikh, Christian and Jain will be given a chance to prove their citizenship and persons belonging to Muslim faith will not be given the same. Many people belonging to nomadic and denotified tribes who are not Muslim will also possibly get this opportunity. But in order to prove their citizenship, they will have to demonstrate that their ancestors were also born in this country. As seen in the incident from the story quoted above, there are generations of people who could never enter schools or could never become permanent residents of any village and could never furnish such proof. It is impossible that the lawmakers are unaware of this fact and if in fact they are aware, then it is safe to say that this amendment to the act has been implemented without any understanding of the cultural diversity or the ground level situation of the people of this country. If this is true, then the intellectual capabilities and intentions of these lawmakers becomes suspect. If these people did not have the necessary intellectual capabilities, they would not have been able to govern a country of 130 crore people.That is why, their intention seems doubtful here. The section of society that is thus unable to fulfill the criteria for citizenship according to this new law has not been formed without context, but because of historical oppression. This historic oppression is based on caste discrimination. The people in power have full knowledge of this and they create conducive environments for such oppression through these laws.

In the year 1871, the British empire declared a few tribes who were a part of Indian society as criminal tribes and gave orders to keep constant surveillance on them. It was made compulsory for them by law to take permission from the police patil of any village before setting up their huts outside the village. If they did not have the documents demonstrating this permission, they were not allowed to stay in that place. In the year 1952, amendments were made to this law and it was renamed as habitual offenders act. As a result many of the Nomadic communities started being recognized as 'denotified tribes' instead of 'criminal tribes'. But the gaze of society and police towards them which sees them as criminals has not changed to this day.

Denotified, Nomadic and Semi Nomadic Tribes are the most neglected marginalized and economically and socially deprived communities. And Colonial gaze of misunderstanding and mislabelling the communities one for others due to certain common practices among the communities such as in book Valley of Kashmir (Lawrence, 1895). "Sometime during the Mughal rule, and for most only after the colonial rulers' policy interventions beginning from 1857 and usurping their resources, and also denying them access to their traditional capital through different enactments, including the Criminal Tribes Act of 1871, Forest Act of 1878, and revenue policies beginning with Permanent Settlement of 1793." ([Renke 2008:95](about:blank)).

"The same colonial legacy has continued even in Independent India. These communities were never consulted by the policymakers while plans for their development were being drawn. To state the truth, the policies of the colonial rulers, as well as of the successive governments of independent India, did irreparable damage to these communities in making them adopt a criminal way of life, and if not to this, then to their impoverishment and marginalisation, as happened with non Criminal Tribes of nomads and semi-nomads, Why communities became what they became was because of the historical context of the rule, an attack on their livelihood, and their oppression." ([Renke 2008:95](about:blank))

\
