# **Background**

## Overview/Historical background/Problems/ Marginalisation of NT, DNT, and SNT Communities

Roughly 150 million [(Renke, 2008)](https://www.zotero.org/google-docs/?Gu7xId) people currently practising different forms of Nomadic livelihoods in India. Some are more close to an egalitarian form much romanticised such as Nomadic-Pastoralism while others have been enforced by the Caste system such as Begging, Prostitution, Dancing Tribes, working in some of the most degrading forms of livelihoods. Alone Nomadic-Pastoral unofficially counts around 40 millions. Laws are made to repress Nomads, stereotypes are peddled as much in the larger society, in media and academia. Criminality as a form of identity made to be a part of hundreds of tribes, even when the law [(Criminal Tribes Act 1871, n.d.)](https://www.zotero.org/google-docs/?KlJish) was repealed (Denotified) in 1952 criminality remained intact as ex-criminals and Habitual offenders [(Sonavane et al., 2020)](https://www.zotero.org/google-docs/?emWMgm). Through the Criminal Tribes Act of 1871, 237 Nomadic Tribes were tagged as criminals.

The Ayyangar Committee report recommended the repeal of the Criminal Tribe Act (CTA) to the Government of India. Resulting in Criminal Tribes Laws (Repeal) Act, 1952 and was enacted based on this recommendation. The act de-notified the people who were previously called criminals, and these people are now referred to as 'De-notified Tribes' (DNTs). The qiuality of life the nomadic people is worse off, due to the peculiarity their social and spatial location in the society. Due to zero presence in the national or state politics the condition of Nomadic communities were never highlighted or even mentioned in policy level or anywhere where in the power structures. It is no irony that till now when we have to understand or have to lack of information about the nomadic communities' Colonial documents are the place to look for the same. And till now only one commission were ever sat down to just 'gather' some basic information on the nomadic communities. Which, itself relied on the earlier mentions database and selective survey. Hence rendering it incomplete to properly numerating the number of all the nomadic communities. The communities which are left and were never recognized at the first place but practice nomadism.

Currently there is no official record mentioning the exact number of nomadic communities in India. There are some documents available in grey literature and some reports produced by some NGO's. The information pertaining to other forms of Nomadism beside Pastoralism is completely ignored by everyone. IIM ahmedabad report with ILLSE (cite report here) tried to collate some information but suffered from lack of information and doesn't tell if authors ever visited any of the community. The report runs on assumptions e.g. The Muslim Gujjar Pastorals of Himachal and Uttrakhand were assumed to be from Gujarat and Gojri is tagged as Gujarati instead.  This information pertains to Pastorals with whom some of the organizations work and take funding on the names of Sustainability and ecology.  Of course, there is scarcely anything available to look for the information regarding hundreds of Nomadic communities. This cycle of disinformation and misinformation about the existence of hundreds of Nomadic tribes leads to furthering of marginalization.

"The livelihoods of non-pastoral nomads were largely affected by mechanization, industrialization and emergence of modern entertainment technologies." ([Renke 2008:97](about:blank)). while at the same time the dance and music of the nomadic communities has been appropriated and given a spiritual angle and specifically held with the Bhramins. However, the real producers of such knowledge were left out and made to disappear their art from their hands. ([note on p.97](about:blank))

Historically Nomadic communities remained outside the framework of the Nomadic societies. However, the complexities which inhabit the Nomadic communities of India makes it difficult for many to take it further. Through Dr. Ambedkar's idea of "Broken Men' we can trace this complexity of nomadic communities of India. We do not know when 'Caste' and Nomadic Societies intersected. But we do know that Prostitution, Begging, Dancing and Singing for Brahmins, Playing Musical Instruments are the product of Caste. We do not know the exact time period when this might have happened. However, 'Broken men' tell a similar narrative when Artisan and Craftsmen were condemned as unclean untouchables.

\
