# Criminality a bitter feature of Identity

## Ex-criminals by birth

"If the State, which is supposed to look after the welfare of its citizens, becomes the tormentor, who can rescue its subjects and to whom can they look up to for help. This is exactly the dilemma that the Denotified and Nomadic communities have been facing since the British rule. Prevailing situation today calls for an overhaul of law enforcement and civil administration. It also requires educating the general public/civil society about these communities to remove the false images that they have developed about these communities." ([Renke 2008:103](about:blank))

150 million individuals [(Renke, 2008)](https://www.zotero.org/google-docs/?Hms0Pf), better known as the Denotified Tribes (DNT) of India, continue to be considered 'criminal by birth'. By 1924, the Act was finally applicable to the whole of British India. Along with the introduction of laws such as the Forest Acts and the Salt Tax Act, the British threw a noose around the lives of DNTs using stringent regulations. And independent India settled with the Habitual Offenders Act (HOF) while denotifying the Tribes. Which functioned as an extension of the criminal Tribe Act [(Reddy, 2018)](https://www.zotero.org/google-docs/?8a0BSG).

"Most of the Denotified and Nomadic community members face abuse of human rights by the law enforcing authorities, realtors, politicians, landlords, and the village communities. They are exploited by every one of them. They are many a time victims of the misuse of power by the police and the caste communities in the villages" ([Renke 2008:92](about:blank))

When there was a court case against you even before you were born. Creating and ascribing that Criminality to a big chunk of your identity. With the removal of such a law, the 'Criminality as Identity' for the NT-DNT community was never removed. Words like 'Ex-criminal, earlier criminal tribes in academic as well in popular media made the community look as some degenerates who need saving. But, at the same time, caste violence served the vehicle to saving. Today NT-DNT has become the 'orient' who is illiterate, irrational, superstitious, doesn't understand anything and is self-indulgent.

Several laws enacted by the Government of India have affected the livelihoods of the Denotified, Nomadic and Semi-Nomadic communities. For instance, Criminal Tribes Act (subsequently repealed in 1952 but replaced by Habitual Offenders Act), Indian Forest Act (its subsequent versions), Wildlife Protection Act of 1972, Land Acquisition Act of 1984, Prevention of Beggary Acts (States) adopting antiquated Bombay Prevention of Begging Act, 1959, The Drugs and Magic Remedies (Objectionable advertisements) Act 1954, Excise Act of 1944, Environment Protection and Biodiversity Conservation Act of 1999, Prevention of Cruelty to Animals Act, 1960, etc. have affected the Denotified, Nomadic and Semi-Nomadic communities by denying them access to the resources, to which they had traditional rights, and deprived them of their livelihoods. In fact, it made them criminals overnight without offering them any sustainable alternatives. The callousness of the State has only increased the misery of these communities and increased their vulnerability. ([Renke 2008:99](about:blank))

> "The stigma of criminality and the consequent harassment of Denotified & Nomadic Tribes is the major problem affecting crores of people in the whole of the country" ([Renke 2008:130](about:blank))

\
