# **Lack of constitutional safeguards**

Most of the current generation is the only first-generation learners. Not having documents not only have impacted the older generations but the impact has belled into future generations. Many of the first-time learners never get admitted into schools, those who can get admission they drop out before the secondary school or even at primary. As documents such as Date of Birth, School, Ration card, Election card are complementary to each other having one document increases the chance of getting another and increasing the chance of having access to better services. Which in most cases for the nomadic and Transgender community in nowhere to be seen?

"The Denotified and Nomadic communities in addition also carry a stigma along with the decline of the relevance and feasibility of their traditional occupations. Whenever there are any development projects like construction of dams, industries, mining, etc.), which require rehabilitation, these communities never receive any benefits, in spite of being evicted from their traditional places of living and work, as they lack any record of rights or rights of residence. All these impact their livelihoods and throw them out of gear with their lives (Renke 2008)."

"There are varied reasons for the perpetuation of atrocities on these communities, the major one being the colonial rule. In a way, they are the helpless victims of the wronged past as well as the present due to deliberate orchestration of falsehood by the dominant groups or interests.  They behave as if they are the rulemakers and take law into their hands, and harass these helpless and poor members of the communities.  Denotified and Nomadic communities encounter many a humiliation, and both verbal and physical abuse for meeting their basic needs, like food and shelter, and in accessing amenities like drinking water, fuel, fodder, burial place for their dead, etc. They are constantly hounded out, living in grip of fear and threat for their existence.  Many a time, the complaints from the Denotified and Nomadic communities are not even registered, leaving aside their expediting. An important fact that the Renke Commission learnt was that the law-enforcing agencies were under severe pressure from middle and upper classes to book ragpickers, and deal with them sternly, for they thought that 'today's ragpickers would" ([Renke 2008:107](about:blank))

\
