# **Indian Citizenship, Politics of Documentation and NT-DNT and SNT Communities**

According to the Renke Commission, people belonging to NT and DNT communities form 15% of the total population of India. 50% of these people don't have any documents signifying their community. There are over 350 castes, tribes, and sub-castes in Maharashtra only. Till 1990, people from NT/DNT communities were not allowed to set up their temporary homes in one place for longer than three days. This restriction was implemented by the Sarpanch, the police, and by common villagers. People from nomadic communities were not allowed to live in villages in order to maintain the caste economy. They were not allowed to participate in the affairs of the feudal castes or the village society. They were restricted from accessing production processes and the only roles they could play were limited to providing entertainment or a select few other services. Because people from these communities were always on the go, the government never had to work towards providing basic citizenship rights such as water, electricity, education, healthcare etc. The population of many of people from many of these tribes is less, and that is why it is easier for settled castes to dominate them. 

The Constitution of India promises 'one vote per person', but one needs an address proof and ration card to apply for a voter ID card. People from nomadic and denotified communities rarely hold these documents and as a result, historically, they have rarely participated in India's democracy. Similarly, many of them do not have legal rights to property. Most people don't have caste certificates, aadhar cards, address proofs, voter ids, etc. Even those like the Wadar community who have given up their nomadic lifestyle and settled in Mumbai have not been able to access these documents. 

Not only do these people not have an address proof, there is no machinery in place for them to prove that they are migrating in a certain region/state. The ones who have settled are not permitted to build permanent houses in villages. For example, people from the Masan Jogi community are only allowed to stay in the village cemetery and they don't have the right legal documents for these residences.

The National Register of Citizens (NRC) is a register maintained by the Indian Government entering names & certain relevant information for identification of Indian citizens of the Assam state. The register was specifically made for Assam state in 1951 to draw up a list of citizens(Bhaumik & Purkayastha, 2020). The list excluded nearly two million people from among the residents of Assam. The state deemed them to have failed to prove that they were Indian citizens (India Exclusion Report, 2020, p. 191).

According to Professor Narayan Bhosale, people from nomadic and denotified communities do not have the documents necessary for the NRC. Because they lead a nomadic lifestyle, they cannot always keep such documents with them. Many people lose their documents in accidents, rain storms, or other natural disasters. Nomadic people do not have the necessary information or reason needed to keep their documents safe for their next generation. Even if they want to settle, they are not accepted in the village. If they want to access the Gruhanirman Yojana, they need to create their address proof document. Such certificates should be given by gram panchayat or the revenue office, but they are not. At most, they may have the permission document given by the police acknowledging their nomadic lifestyle which lets them travel from one village to another. These documents are usually kept only till their purpose is served. Professor Bhosale further stipulates that the class in power has spread various rumours about nomadic and denotified communities so that they are denied entry into villages. They were not allowed to join the dominant culture of society, and neither were there any efforts made to understand the nomadic culture. Alternatively, nomadic communities' culture and science was never allowed to have a respected place in dominant culture. Even if nomadic communities find a place among other settled communities, they are given a lesser position in the hierarchy.

\
