# **Methodology**

We started with discussions on the issues related to the Nomadic communities. Among many NRC and CAA, which we think is going to have the most adverse impact on the different nomadic communities residing sparsely all over India. We discussed what could be the issues a Nomad might face to prove their citizenship. It was apparent even before the start of a discussion to have a provable answer. How can a nomad prove that they are a Citizen. Those who have worked with the Nomadic?  Does a Nomad have the written documentary proof to show that they belong to India and are its citizens without the fear of being thrown into a detention centre? If one's livelihood is such that they in most cases do not have such proofs.

We discussed and gave an outline to the research i.e. how we should move and have a survey during the Covid19 pandemic. We discussed the questionnaire in multiple meeting to frame the proper questionnaire. Before going on to collect the data based on the questionnaire. We hired and trained the Local Youth from the community. Although the researchers who are involved in the research, all of them from different Nomadic communities and are well aware of the complexities and intersectional issues.

We trained two surveyors from the community and provided them with the designed survey. We rested on a target of getting 100 household surveys in a month. In the meantime, we did the online literature research on databases such as google scholar and a regular google search with Keywords such as Nomadism, Citizenship, Criminalization, Vulnerability, NRC, CAA. We meet regularly through Zoom and Google meet to discuss the literature and the Surveyors we received.

After taking 30 household surveys we decided to review the findings. By doing so we wanted to minimize any whatsoever shortcomings might later feature in the final document. And we reframed 6 questions and reduced the importance of a few others for the sake of simplicity and to make a better sense. After 30 days we received 106 surveys and google form proved to be not useful to generate better charts. We downloaded all the responses and did the analysis in excel using pivot tables.

### Cleaning the Data

We divided the questionnaire into further three sub groups. First, Short Responses where the response was 'yes/no' or on similar responses-to do a fast analysis. Second, the Thematic Questions (responses), where the responses are longer and need more of a qualitative analysis. Third, The Demographic Questions, the purpose of the sub group Demographic is to the basic information of the communities.

### **Challenges**

The challenges we faced during the research are choosing the location for the study. Historically the settlements in Colonial Bombay were the places where a large number of Nomadic communities lived. Ambernath being a distinct place where many Nomadic communities from different states live here makes it a perfect place to understand various issues concerning the nomadic communities.

The other challenge Covid-19 pandemic lockdown, travelling and taking interviews during this time is a big challenge. Fortunately, our field researchers are from the community itself and reside in the same area. This also ensured the reliability of the data as the community was more open and welcoming to someone from the community itself.

### **Participants of the study**

A total of 107 in-depth interviews are taken from among the different Nomadic communities from the Ambernath area in the Thane district of Maharashtra. We found that 86.7% are practising nomadism regularly while 11.4 % are practising it sometime. A practice to earn a livelihood based not only on constant migration from one place to another but with extreme vulnerability to exploitation. From the same number of communities, 98.1% don't own a house which is to say that 98.1% are living in **tents**. With constant mobility due to historical caste discrimination and invibilisation at the policy level.

\
