# **Colonialism coupled with Brahminical governance**

It is to the Brahmanvaad's benefit that caste and patriarchy are not destroyed and so they have ensured that the law of Manusmriti has been accepted and applied through the ages. That is why, nobody except those belonging to upper castes have had access to basic needs such as food, clothing, shelter, and education fulfilled or received the rights to freedom, equality, free speech, protection from exploitation, freedom of religion, which are owed to every citizen of India. Essentially, there has been continuous struggle on the part of Dalit, Bahujan, Nomadic and Denotified communities, Adivasis, and especially women from all communities, religious minorities to receive these rights. The constitution and its law was always by their side in this struggle but people with a Manuvadi mindset asserted their dominance over constitution and justice by bringing about a series of changes that suited them best. The recent amendment to the Citizenship Act and Amit Shah's announcement of the NRC was a part of the same series.

According to the Citizenship Act of 1955, a person born in India before 26 January 1950 or after that up till 1 July 1987, or according to the 2003 amendment, on 1 July 1987 or a person born in India before the 2003 amendment was enforced, or a person whose parents were both citizens of India at the time of the 2003 amendment, or whose one parents was an Indian citizen and the other wasn't an illegal intruder would be recognized as an Indian citizen. According to the Constitution of India, every citizen has some fundamental rights through which the architects of the Constitution have aimed to bring Indian society, which is marked by inequalities, closer to equality. But because power went straight to those who uphold Brahminism after independence, they have made strict arrangements from all directions to ensure that the Constitution is not fully enforced.

Only under a Brahmanvadi system can those ruling this country be unaware about how such an irresponsible and inconsiderate response from a government in the 21st century denies citizenship to a large number of people.'Nomadic and migratory tribes' have been mentioned in the seventh list of the Constitution but not a single party which has been in power since Independence has thought about including or tried to include them in the census. The protection accorded to all citizens of India have been mentioned in the same list, but people from nomadic and denotified tribes have never received any Constitutional rights or security. It is a fact that they have to struggle even for basic human rights. For those who have to struggle even to get a caste certificate, benefiting from reservation is a distant dream. As a result of the Dalit Panthers movement of the 70s and the movements of the 90s of nomadic and denotified communities, the government set up committees to study this subject. Even in these committees, only a handful of people from the community found representation. Accordingly, Dr. Leenkumar Bavne says, "A person's social status is decided based on their citizenship, freedom, and their relationship with the family, but people from nomadic communities have never received freedom of citizenship.

A large number of Muslim and Dalit-Bahujan citizen had been opposing the Citizenship Amendment Bill since it came up for discussion in the parliament. The bill was passed in total disregard of this opposition. According to the Act, persecuted Hindus, Buddhists, Parsi, Jain, and Christian minorities who seek asylum in India will be granted Indian citizenship, but Muslims citizens from the same countries will not. Further, the Act says nothing about asylum seekers from other countries such as Sri lanka and Myanmar with which India shares a border. After passing this act, the implementation of the NRC was announced in Parliament. To have one's name registered in the NRC, each citizen would have to prove that their ancestors were born in India and anyone who couldn't prove this would be stripped of their citizenship and have to reapply. This was the strange 'demonetization' plan hatched by those in power. Those who feared that they would be impacted by this law and would lose even the right to fight for all the fundamental rights they had never received began resisting this.

These questions posed by Mane are the questions of 15% of India's nomadic and denotified tribal communities. This '15%' is not a figure of the census but has been derived from first the Renke and then the  Idate commisson surveys. The government has never thought about how to include nomadic communities who wander for sustenance and to preserve their culture, in the census. When TN Pratapan presented this question before Social Justice and Empowerment Department parliament, he received this response on 4 February 2020: The government has not taken any strategic decision to include Nomadic and Denotified communities in the 2021 census.

\
