# **Nomadism**

The word "nomad" is derived from Latin through Gk.﻿ nemō, meaning either "pasture" or "distribute." The simplest definition of a nomad is a person who must keep moving to gain basic life sustenance. Nomadism is usually the product of a sparse environment, weather patterns (sometimes seasonal), or economic or political shifts making mobility essential for survival. It does not properly apply to immigrants (Boraas, 2011).

For thousands of years Nomadic communities travelled, moved from one place to another for reasons including; in search of livelihood, cultural association, grazing for their livestock which is no less an ecological reason, a borderless world thus attaching a 'Placelessness' to their identity. Sometimes such 'migrations' are forceful and are due to the animosity of the settled civilization towards the nomadic communities.

Nomadism is considered a practice of migration from one place to another in search of livelihood. However, the simplistic understanding of 'migration' doesn't explain the word in its length and the breadth-the idea that there is 'placelessness' which is inherent to nomadism makes it different from the casual reading of 'Migration'. Most of the work in India happened on arid area nomadism in India such as Raikas, Rabadi's of Rajasthan and to some extent in Gujarat (Kavoori, 2005; Agrawal, 1992) and similarly in Africa with the Boran, Rendilli, Masia (E. Fratkin, 1998; E. M. Fratkin et al., 1999). Hardly answer such a complicated question. Most of these studies are limited to animal husbandry or ecological sensibilities of the communities. At the same time the

"The Segovia Declaration of Nomadic and Transhumant Pastoralists, 2007, also reflects on the reasons for the trials and tribulations of the nomadic pastoral communities across the globe. It says, In many societies, governments have"nationalised" and confiscated rangelands, forests and other natural resources on which pastoralists depend, removing them from community care, control and property and alienating nomadic pastoralists from their natural rights. In the meantime, current neoliberal economic and social policies globally impose the privatization of natural resources including life itself. These have resulted in an unprecedented concentration of economic and political power in the hands of very few elites throughout the world. These policies are destroying the livelihoods, environment, nature, and culture, including the spiritual values and dignity of pastoralists and other rural communities. Our rural areas are faced with conflict and war and are becoming empty as our people countries'. migrate to cities and other" ([Renke 2008:97](about:blank))

\
